Submarine Bucket Use Toggle
mrmin123/kancolle-auto pull request #364
Opened 2017-05-06 03:24 UTC by R-Jimenez

Feature outlined in #354.

2017-05-06 06:34 UTC, mrmin123 requested changes
Requested some changes in `config.ini` and `config_detailed.ini`. Code changes looks good but I'd also like to test it a bit before merging.

2017-05-06 06:34 UTC, mrmin123 commented on config.ini
> +UseBuckets = false
Please change `false` to `False` (`ConfigReader` can deal with `false`, but to keep in-line with Python standards). If you could also update `config_detailed.ini` with this new parameter and add a description of what it does that'd be great.

2017-05-06 06:42 UTC, mrmin123 commented on kancolle_auto.sikuli/combat.sikuli/combat.py
> +                                if global_regions['repair_panel'].exists(Pattern('ship_class_ss.png').similar(0.8)) or global_regions['repair_panel'].exists(Pattern('ship_class_ssv.png').similar(0.65
There's a `CLASS_SIMILARITY` constant defined at the beginning of the file. Was this not sufficient for `ship_class_ss` and `ship_class_ssv`? I'd like to set the threshold for all ship class matching to a constant if at all possible.

2017-05-06 22:19 UTC, R-Jimenez commented on kancolle_auto.sikuli/combat.sikuli/combat.py
> +                                if global_regions['repair_panel'].exists(Pattern('ship_class_ss.png').similar(0.8)) or global_regions['repair_panel'].exists(Pattern('ship_class_ssv.png').similar(0.65
Will have to lower CLASS_SIMILARITY to about .65 if that's the case. I tried a couple environments but the SSV icon is tricky to match, especially with dmg effects.

2017-05-09 01:24 UTC, mrmin123 commented
Thanks for the update. As an FYI, an FYI, I am going to defer feature additions until post-event. I'd also like to look into the CLASS_SIMILARITY value a bit more before merge. Depending on the needed values the approach to the constant might have to change.

2017-05-09 13:09 UTC, R-Jimenez commented
Roger that. o7 I feel like having a high CLASS_SIMILARITY is worth it, since only one or two classes are tricky enough to warrant a lower setting for accurate searching. Why not just have two tiers? CLASS_SIMILARITY and CLASS_SIMILARITY_LOW/CLASS_SIMILARITY_SSV?

2017-05-22 08:34 UTC, mrmin123 commented
@R-Jimenez please separate out the `0.8` and `0.65` thresholds to additional globals at top of `combat.py` as `CLASS_SIMILARITY_SS` and `CLASS_SIMILARITY_SSV` and reference those in the code. It'll help during refactor so I can keep track of globals.

2017-05-22 13:43 UTC, R-Jimenez commented
Changes pushed.

2017-05-22 15:11 UTC, mrmin123 commented
@R-Jimenez It looks like some unrelated changes got pushed with your latest commits. Please revert those, merge in master, and repush the branch.

2017-05-22 16:02 UTC, R-Jimenez commented
Sorry about that. Git had some confusion with the branches and pulled files I thought were not committed. Should be much cleaner now

2017-06-01 03:39 UTC, merged